macrovue/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from home import views
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = patterns('',
    # make this the home page
    url(r'^$', 'vues.views.index', name='index'),
	#if not logged in, index page
    url(r'^index/$', 'vues.views.index', name='index'),
    url(r'^index$', 'vues.views.index', name='index'),
    # for comments
    url(r'^comments/', include('django.contrib.comments.urls')),
    #display the vue
    url(r'^vues/(?P<vue_name>[-\w ]+)/$', 'vues.views.show', name='single_vue'),
	# customise the vue
    url(r'^vues/(?P<vue_name>[-\w ]+)/customise$', 'vues.views.customise', name='customise_vue'),
	# create a vue
    url(r'^create_vue$', 'vues.views.create_vue', name='create_vue'),	
	# create a vue
    url(r'^save_new_vue$', 'vues.views.save_new_vue', name='save_new_vue'),	
	# save the custom vue
    url(r'^save_custom/$', 'vues.views.save_custom', name='save_custom'),	
	# add the vue as a favourite
	url(r'^vues/addfavourite/(?P<vue_name>[-\w ]+)$', 'vues.views.addfavourite', name='add_favourite'),
	# add the vue as a favourite
	url(r'^vues/removefavourite/(?P<vue_name>[-\w ]+)$', 'vues.views.removefavourite', name='remove_favourite'),
	# submit a rating for a vue
	url(r'^vues/submit_rating/(?P<vue_id>\d+)/(?P<rating>\d+)$', 'vues.views.submit_rating', name='submit_rating'),
	# get stocks for that vue
    url(r'^getstocks/(?P<ticker_name>[-\w ]+)/(?P<index>[-\w ]+)$', 'vues.views.getstocks', name='get_stocks'),
    # get their financials
    url(r'^getstockfinancials/(?P<ticker_id>\d+)$', 'vues.views.getstockfinancials', name='get_stock_financials'),
	# get the vues
    url(r'^getvues/(?P<menu>\d+)$', 'vues.views.getvues', name='get_vues'),
    # view profiles
    url(r'^profile/(?P<username>[-\w ]+)$', 'users.views.view_profile', name='view_profile'),
    # settings
    url(r'^settings$', 'users.views.profile_settings', name='profile_settings'),
    # get vue returns
    url(r'^getvuereturns/(?P<vue>[-\w ]+)$', 'vues.views.getvuereturns', name='get_vue_returns'),
	# get a list of vues
    url(r'^existing_vues$', 'vues.views.list', name='existing_vues'),
    # get a list of users vues
    url(r'^users_vues$', 'vues.views.users_vues', name='users_vues'),
	# the blog link
    url(r'^blog/', include('zinnia.urls')),
	# the generic comments
    url(r'^comments/', include('django.contrib.comments.urls')),
	# subscribe to the mailing list
    url(r'^subscribe/$', 'vues.views.subscribe', name='subscribe'),
	# admin cp
    url(r'^admin/', include(admin.site.urls)),
	# register to the site
    url(r'^register/$', 'users.views.register_view', name='register'),
    url(r'^register-submit/$', 'users.views.register', name='register_submit'),
    #does username or email exist
    url(r'^usernamecheck/(?P<username>[-\w ]+)$', 'users.views.username_check', name='username_check'),
    url(r'^emailcheck/(?P<email>[\w.%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})$', 'users.views.email_check', name='email_check'),
    # activate account
    url(r'^activate/(?P<activation_id>[-\w ]+)$', 'users.views.activate_account', name='activate'),
	# login
    url(r'^login/$', 'users.views.login', name='login'),
    url(r'^login/$', 'users.views.login', name='auth_login'),
	# logout
    url(r'^logout/$', 'users.views.logout', name='logout'),
    # about
    url(r'^about/$', 'home.views.about', name='about'),
    # faq
    url(r'^faq/$', 'home.views.faq', name='faq'),
    # my favourites page under my accounts 
    url(r'^favourites/$', 'vues.views.favourites', name='favourites'),
    # custom vues
    url(r'^customvues/$', 'vues.views.customvues', name='customvues'),
    # portfolio 
    url(r'^portfolio/$', 'vues.views.portfolio', name='portfolio'),
    #getting the portfolio values for the graph json
    url(r'^getportfolio/(?P<date_n>\d+)$', 'vues.views.getportfolio', name='getportfolio'),
    url(r'^getportfolio_percent/(?P<date_n>\d+)$', 'vues.views.getportfolio_percent', name='getportfolio_percent'),
    #portfolio-returns 
    url(r'^portfolio-allocations/$', 'vues.views.portfolio_allocations', name='portfolio_allocations'),
    #get-allocations-country
    url(r'^getallocations-country/$', 'vues.views.getallocations_country', name='getallocations_country'),
    #orders - checking status 
    url(r'^orders/$', 'vues.views.orders', name='orders'),
    #buy - purchase the stocks in that vue
    url(r'^buy/(?P<vue_name>[-\w ]+)/$', 'vues.views.buy', name='buy'),
    #place_order - sends orders to the zeroMQ
    url(r'^place_order/$', 'vues.views.place_order', name='place_order'),
    #view transactions
    url(r'^transactions/$', 'vues.views.transactions', name='transacitons'),
    #view statements
    url(r'^statements/$', 'vues.views.statements', name='statements'),
    #funding
    url(r'^funding/$', 'vues.views.funding', name='funding')
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from django.db import models
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User
from django.conf import settings

class RegisterForm(UserCreationForm):
	# declare the fields you will show
	username = forms.CharField(label="Username")
	# first password field
	password1 = forms.CharField(label="Password")
	# confirm password field
	password2 = forms.CharField(label="Repeat your password")
	email = forms.EmailField(label = "Email Address")
	first_name = forms.CharField(label = "First Name")
	last_name = forms.CharField(label = "Last Name")

	# this sets the order of the fields
	class Meta:
		model = User
		fields = ("first_name", "last_name", "email", "username", "password1", "password2", )

	# this redefines the save function to include the fields you added
	def save(self, commit=True):
		user = super(RegisterForm, self).save(commit=False)
		user.email = self.cleaned_data["email"]
		user.first_name = self.cleaned_data["first_name"]
		user.last_name = self.cleaned_data["last_name"]
		if commit:
			user.save()
		return user
		
class UserModel(models.Model):  
	user = models.OneToOneField(User)
	avatar = models.ImageField(upload_to="avatars/",blank=False)
	biography = models.CharField(max_length=140, default='')
	facebook = models.CharField(max_length=300, default='')
	twitter = models.CharField(max_length=300, default='')
	linkedin = models.CharField(max_length=300, default='')
	first_name = models.CharField(max_length=300, default='',blank=False)
	last_name = models.CharField(max_length=300, default='',blank=False)
	email = models.CharField(max_length=300, default='',blank=False)
	
	class Meta:
		db_table = "user_model"
		verbose_name_plural = "UserModel"
		
	def get_avatar(self):
		if not self.avatar:
			return settings.STATIC_URL+"images/macrovue_small_logo.png"
		else:
			return settings.MEDIA_URL+str(self.avatar)

users/forms.py
from django import forms
from users.models import UserModel

class ProfileForm(forms.ModelForm):
	biography = forms.CharField(required=False, widget=forms.Textarea(attrs={'placeholder': 'Enter your biography here'}))
	facebook = forms.CharField(required=False, widget=forms.TextInput(attrs={'placeholder': 'Enter your Facebook profile link here'}))
	twitter = forms.CharField(required=False, widget=forms.TextInput(attrs={'placeholder': 'Enter your Twitter profile link here'}))
	linkedin = forms.CharField(required=False, widget=forms.TextInput(attrs={'placeholder': 'Enter your Linkedin profile link here'}))
	avatar = forms.FileField(required=False,initial='images/macrovue_logo_small.png')
	first_name = forms.CharField(required=False, widget=forms.TextInput(attrs={'placeholder': 'Enter your first name here'}))
	last_name = forms.CharField(required=False, widget=forms.TextInput(attrs={'placeholder': 'Enter your last name here'}))
	email = forms.CharField(required=False, widget=forms.TextInput(attrs={'placeholder': 'Enter your email here'}))
	

	class Meta:
		model = UserModel
		fields = ('first_name','last_name','email','biography','facebook','twitter','linkedin','avatar')

users/views.py
from django.shortcuts import render, render_to_response, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import auth, messages
from django.contrib.auth import authenticate, login
from django.template import RequestContext
from vues.models import UserActivated
from django.core.mail import send_mail
from users.models import RegisterForm
import mandrill, os, binascii
from users.models import User, UserModel
from users.forms import ProfileForm

from vues.models import Vues, VueFinancialData

from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
from django.utils.html import strip_tags

# register to the website
def register(request):
	if request.method == 'POST':	
		form = RegisterForm(request.POST)
		if form.is_valid():
			new_user = form.save()
			messages.info(request, "Thanks for registering. You are now logged in.")
			new_user = authenticate(username=request.POST['username'], password=request.POST['password1'])
			auth.login(request, new_user)
			random = binascii.b2a_hex(os.urandom(15))
			UserActivated.objects.create(user_id=request.user.id,isActivated=False,randomText=random)
			UserModel.objects.create(user_id=request.user.id,avatar='avatars/macrovue_small_logo.png',
			first_name=request.POST['first_name'],last_name=request.POST['last_name'],email=request.POST['email'])
			subject, from_email, to = 'Welcome to Macrovue', 'sid@macrovue.com.au', request.POST['email']

			html_content = render_to_string('mail.html', {'username':request.user.username}) # ...
			text_content = strip_tags(html_content) # this strips the html, so people will have the text as well.

			# create the email, and attach the HTML version as well.
			msg = EmailMultiAlternatives(subject, html_content, from_email, [to])
			msg.attach_alternative(text_content, "text/html")
			msg.content_subtype = "html"
			msg.send()
	
			return HttpResponseRedirect("/existing_vues")
		else:
			return render(request, 'users/register.html', { 'form': form })

	return render(request, 'users/register.html', { 'form': form })

def register_view(request):
	form = RegisterForm(auto_id=True)
	return render(request, 'users/register.html', { 'form': form })

def username_check(request, username):
	num = User.objects.filter(username = username).count()
	return HttpResponse(num)

def email_check(request, email):
	num = User.objects.filter(email = email).count()
	return HttpResponse(num)

# login to the website
def login(request):
	username = request.POST.get('username', '')
	password = request.POST.get('password', '')
	user = auth.authenticate(username=username, password=password)
	if request.method == 'POST':
		if user is not None and user.is_active:
			# Correct password, and the user is marked "active"
			auth.login(request, user)
			# Redirect to a success page.
			return HttpResponseRedirect("/existing_vues")
		else:
			messages.error(request, "Invalid Username or Password")
			return render_to_response('users/login.html', locals(), context_instance=RequestContext(request))
	else:
		return render_to_response('users/login.html', locals(), context_instance=RequestContext(request))

# logout of the website
def logout(request):
	auth.logout(request)
	# Redirect to a success page.
	return HttpResponseRedirect("/index")
	
@login_required
def activate_account(request,activation_id):
	# grab this users specific id
	activatedInfo = UserActivated.objects.get(user_id=request.user.id)
	if (activation_id == activatedInfo.randomText and activatedInfo.isActivated == False):
		activatedInfo.isActivated = True;
		activatedInfo.save()
		return HttpResponse("Successfuly activated your account.")
	elif (activatedInfo.isActivated == True):
		return HttpResponse("Your account is already active.")
	else:
		return HttpResponse("You need to use the correct code in your email.")

def view_profile(request,username):
	if (User.objects.filter(username=username).exists()):
		profile = User.objects.get(username=username)
		profile_info = profile.get_profile()
		vues = Vues.objects.filter(user=profile,is_visible=True)
		vue_financial_data = VueFinancialData.objects.filter(vue__custom_vue__isnull=False,vue__user=profile).order_by('date')
		return render_to_response('users/profile.html', locals(), context_instance=RequestContext(request))
	else:
		return HttpResponseRedirect("/existing_vues")
		
@login_required
def profile_settings(request):
	context = RequestContext(request)
	profile = request.user.get_profile()
	if request.method == 'POST':
		form = ProfileForm(request.POST, request.FILES, instance=request.user.get_profile())
		if form.is_valid():
			profile = form.save(commit=False)
			profile.user = request.user # Set the user object here
			profile.save() # Now you can send it to DB
			return render_to_response('users/settings.html', locals(), context)
	else:
		form = ProfileForm(instance=request.user.get_profile())

	return render_to_response('users/settings.html', locals(), context)

templates/users/login.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}MacroVue - Login{% endblock %}
{% block content %}
<link href="{% static "css/login.css" %}" rel="stylesheet" type="text/css"/>
  
<div class="container">
  <div id="login-box">
    <!-- Begin login form -->
<div class="content">
  <h1 class="no_margin"> Login </h1>

{% if messages %}{% for message in messages %}
<div class="error_message"> - {{ message }}</div>
{% endfor %}{% endif %}

  <!-- BEGIN LOGIN FORM -->
  <form class="login-form" action="/login/" method="post">
    {% csrf_token %}
    <div class="username-field">
      <label class="input-labels">Username:</label>
        <input class="form-input" type="text" name="username" id="username">
    </div>
    <div class="password-field">
      <label class="input-labels">Password:</label>
        <input class="form-input" type="password" name="password" id="password">
    </div>
    <div class="button-field">
      <button type="submit" class="submit-button">
        Login
      </button>
    </div>
    <div class="create-account">
      <p> Don't have an account? <a href="/register/">Create an account here</a></p>
    </div>
  </form>
  <!-- END LOGIN FORM -->
  </div>
</div>
</div>
{% endblock %}

templates/users/profile.html
{% extends "base.html" %}
{% load mathfilters %}
{% load humanize %}
{% load staticfiles %}

{% block title %}MacroVue - {{ profile.username }}s Profile{% endblock %}

{% load app_filters %}
{% load comments %}

{% block content %}

<script src="{% static "js/profiles.js" %}" type="text/javascript"></script>
<link href="{% static "css/profiles.css" %}" rel="stylesheet" type="text/css"/>

<div class="container">
	<div id="profile_left_container">
		<div id="profile_left_avatar">
			<img src="{{ profile.get_profile.get_avatar }}" /><br />
			<div id="profile_username">{{ profile.username }}</div>
		</div>
		<div id="profile_quote">
			{{ profile_info.biography }}
		</div>
		<div id="profile_stats">
			<div class="profile_stat_text">Custom Vues</div><div class="profile_stat_value">19</div>
			<div class="profile_stat_text">Comments on Vues</div><div class="profile_stat_value">198</div>
			<div class="profile_stat_text">Macrovue Friends</div><div class="profile_stat_value">372</div>			
		</div><div class="clear"></div>
		<div id="profile_social">
			<div id="add_friend">
				Add Friend
			</div>
			<div id="view_vues">
				View Vues
			</div><div class="clear"></div>
			<img src="{% static "images/facebook.png" %}">
			<img src="{% static "images/twitter.png" %}">
			<img src="{% static "images/linkedin.png" %}">
		</div>
	</div>
	<div id="profile_right_container">
		<div id="profile_menu">
			<div class="profile_menu_option" id="tab1">
				My Portfolio
			</div>
			<div class="profile_menu_option active" id="tab2">
				My Vues
			</div>
			<div class="profile_menu_option" id="tab3">
				Social Feed
			</div>
		</div>
		<div class="clear"></div>
		<div id="profile_content_2" class="profile_content">
			{% for vue in vues %}
			{% for financial in vue_financial_data %}
			{% if financial.vue_id == vue.id %}
			<a href="/vues/{{ vue.name.split|join:"-" }}">
				<div class="existing_vue_default" id="vue{{ vue.id }}">
					<div class="existing_vue_info" style="background: url('{{vue.background}}');">
						<div class="existing_vue_title">
							{{ vue.name }}
						</div>
					</div>
					<div class="existing_vue_return">
						<span class="float_left" style="font-size: 16px; padding-top: 18px; padding-left: 10px;">One month return </span>
						{% if financial.one_mo_return > 0 %}
							<span class="green_return float_right" style="padding-right: 10px;"><i class="fa fa-arrow-up" style="font-size: 26px;"></i>
						{% elif financial.one_mo_return < 0 %}
							<span class="red_return float_right" style="padding-right: 10px;"><i class="fa fa-arrow-down" style="font-size: 26px;"></i>
						{% else %}
							<span class="neutral_return float_right" style="padding-right: 10px;"> -- 
						{% endif %}
						{{ financial.one_mo_return }}%</span>
					</div>
				</div>
			</a>
			{% endif %}
			{% endfor %}
			{% endfor %}
		</div>
	</div>
</div>

{% endblock %}

templates/users/register.html
{% extends "base.html" %}
{% load staticfiles %}


{% block title %}MacroVue - Registration{% endblock %}

{% block content %}
<link href="{% static "css/register.css" %}" rel="stylesheet" type="text/css"/> 
<script type="text/javascript" src="{% static "js/register.js" %}"></script>

	<div class="container">
		<div id="form-box">
			<h1>Register</h1>
			<form class="register-form" action="/register-submit/" method="POST">
				{% csrf_token %}
				{% for option in form %}
					<div class="input-items">
						{% if option.label == "Password" %}
							Password: <input id="password1" name="password1" type="password" /><br />
							<div class="small_size_text pwd_info">Your password must be at least 8 characters long and includes a capital letter, a number and a symbol.</div>
						{% elif option.label == "Repeat your password" %}
							Repeat your password: <input id="password2" name="password2" type="password" /><br />
						{% else %}
							{{ option.label }}: {{ option }}<br />
						{% endif %}
					</div><div class="clear"></div>
				{% endfor %}
				<div id="errors"></div>
				<div class="form-group">
					<button type="submit" id="register_button">Register</button>
				</div>	
				<p class="login-direct">Already have an account? <a href="/login/">Click here to log in</a></p>	
			</form>
		</div>
	</div>
{% endblock %}

templates/users/settings.html
{% extends "base.html" %}
{% load humanize %}
{% load staticfiles %}
{% load form_filters %}

{% block title %}MacroVue - User Settings{% endblock %}

{% load app_filters %}

{% block content %}

<script src="{% static "js/settings.js" %}" type="text/javascript"></script>
<link href="{% static "css/settings.css" %}" rel="stylesheet" type="text/css"/>

	<div id="single_vue_tabs">
		<div class="single_vue_tab green_haze white_to_gray single_vue_first_tab single_vue_active_tab" id="tab1">
			Profile Settings
		</div>
		<div class="single_vue_tab white_to_gray single_vue_final_tab" id="tab2">
			Investor Settings
		</div>
	</div><div class="clear"></div>
	
	<div class="container">
		<div class="profile_settings" id="content_tab1">
			<form action="settings" enctype="multipart/form-data" method="POST" id="create_vue">
			{% csrf_token %}
			{% for hidden in form.hidden_fields %}
				{{ hidden }}
			{% endfor %}
			{% for key, value in form.errors.items %}
				{{ value }}
			{% endfor %}
								
				<div class="settings_row">
				First Name:<input id="id_first_name" name="first_name" placeholder="Enter your first name" type="text" value="{{ profile.first_name }}" /><br />
				</div>

				<div class="settings_row">
				Last Name:<input id="id_last_name" name="last_name" placeholder="Enter your last name" type="text" value="{{ profile.last_name }}" />
				</div>

				
				<div class="settings_row">
					Email:
					<input id="id_email" name="email" placeholder="Enter your email" type="text" value="{{ profile.email }}" />
				</div>
				
				<div class="settings_row">
				Facebook Link:<input id="id_facebook" name="facebook" placeholder="Enter your Facebook profile link here" type="text" value="{{ profile.facebook }}" />
				</div>
				
				<div class="settings_row">
				Twitter Handle:<input id="id_twitter" name="twitter" placeholder="Enter your Twitter profile link here" type="text" value="{{ profile.twitter }}" />
				</div>
				
				<div class="settings_row">
				LinkedIn Link:<input id="id_linkedin" name="linkedin" placeholder="Enter your Linkedin profile link here" type="text" value="{{ profile.linkedin }}" />
				</div>
				
				<div class="settings_row">
				Biography:
				<textarea id="id_biography" name="biography" placeholder="Enter your biography here" maxlength="140">{{ profile.biography }}</textarea>
				<div class="clear"></div><div class="float_right"><span id="bio_counter">{{ profile.biography|length }}</span>/140</div>
				</div>
				
				<br />
				<div class="float_left" id="avatar">
					<img src="{{ profile.get_avatar }}" />
				</div>
				<div class="float_left" id="avatar_block">
				Currently: <a href="{{ profile.get_avatar }}">{{ profile.get_avatar }}</a> :<input id="avatar-clear_id" name="avatar-clear" type="checkbox" /> <label for="avatar-clear_id">Clear</label><br />Change: :<input id="id_avatar" name="avatar" type="file" />
				</div><div class="clear"></div><br />
				<button class="green_button green_haze float_right" type="submit">Update Settings</div>
			</form>
		</div>
		<div class="profile_settings display_none" id="content_tab2">
			Test
		</div>
	</div>

{% endblock %}